server:
  port: 9004

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  rabbitmq:
    host: 123.56.13.218
    port: 5672
    username: root
    password: star11.. 
  redis:
    database: 0
    host: 123.56.13.218
    port: 6379
    password: star11..
    jedis:
      pool:
        max-active: 1
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 1000  
mybatis:
   mapper-locations: classpath*:com/xc/mapper/*Mapper.xml
   config-location: classpath:mybatis-config.xml

